# Potential Field Method Gains
attractive_potential_gain: 10.0
repulsive_potential_gain: 300.0

# Lidar Data Informations
potential_field_distance: 25.0
lidar_distance_max: 25.0          # meters
lidar_distance_min: 0.5           # meters
lidar_angle_max: 1.57619449019    # radian
lidar_angle_min: -1.57619449019   # radian
lidar_data_length: 716
lidar_link_name: front_laser_link

# Lidar Clustering Parameters
n_distance_segment: 4
clustering_threshold: 10          # meters
merging_threshold: 0.4            # meters

# Robot Dynamics Parameters
# Linear
acc_x_lim: 2.5
vel_x_max: 1.0
vel_x_min: 0.1
linear_kp: 5.0

# Angular
acc_theta_lim: 1.5
vel_theta_max: 0.7
vel_theta_min: 0.2


angular_kp: 5.0
angular_kd: 4.0

# Goal Parameters
xy_goal_tolerance: 0.6
yaw_goal_tolerance: 0.1
in_place_vel_theta: 0.2

# Publish cmd_vel if False
check_potential: False